<?php
/******************************************
NL Dutch
Admin Category Language
******************************************/

$lang['categories']					= 'Categorieën';
$lang['error_must_select']			= 'Je moet een categorie selecteren om te ordenen';
$lang['error_not_found']			= 'Kan gevraagde categorie niet vinden.';
$lang['organize_category']			= 'Categorie "%s" ordenen';
$lang['organize']					= 'Ordenen';
$lang['category_id']				= 'Categorienummer';
$lang['category_form']				= 'Formulier categorie';
$lang['name']						= 'Naam';
$lang['slug']						= 'Slug';
$lang['description']				= 'Omschrijving';
$lang['excerpt']					= 'Samenvatting';
$lang['sequence']					= 'Reeks';
$lang['image']						= 'Afbeelding';
$lang['seo_title']					= 'Zoekmachine titel';
$lang['meta']						= 'Metadata';
$lang['message_category_saved']		= 'Deze categorie is bewaard!';
$lang['error_file_upload']			= '<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'Deze categorie is gewist.';
$lang['current_file']				= 'Huidig bestand';
$lang['confirm_delete_category']	= 'Bent u zeker dat deze categorie gewist mag worden?';
$lang['add_new_category']			= 'Nieuwe categorie';
$lang['no_categories']				= 'Er zijn momenteel geen categorieën';
$lang['attributes']					= 'Attributen';
$lang['seo']						= 'Zoekmachine optimalisatie';
$lang['parent']						= 'Bovenliggende categorie';
$lang['meta_data_description']		= 'bv. &lt;meta name="description" content="Wij bieden u de beste producten aan" /&gt;';
$lang['drag_and_drop']				= 'Klik en versleep de producten in de gewenste volgorde.';
$lang['sku']						= 'Productcode';
$lang['price']						= 'Prijs';
$lang['sale']						= 'Actieprijs';
